export const MONITORING_MONGO_CONNECTION = "monitoring-db";
export const MONITORING_QUEUE = "MONITORING_QUEUE";
export const MONITORING_INSERT_DB_LOG = "MONITORING_INSERT_DB_LOG";
export const MONITORING_INSERT_REQUEST_LOG = "MONITORING_INSERT_REQUEST_LOG";
